name: file_manager_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^5.5.0
  path_provider: ^2.1.1
  sqflite: ^2.3.0
  permission_handler: ^10.4.5
  provider: ^6.0.5
  open_file: ^3.3.2
  share_plus: ^7.1.0
  flutter_pdfview: ^1.3.1
  video_player: ^2.7.2
  intl: ^0.18.1
  cupertino_icons: ^1.0.8
  path: ^1.8.0
  google_fonts: ^6.1.0
  flutter_animate: ^4.5.0
  flex_color_picker: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
  fonts:
    - family: Nothing
      fonts:
       - asset: assets/fonts/NothingCLv1.2-Regular.ttf
